const obtenerTurnoPorId = async (req, res) => {
  try {
  } catch (error) {
    res.status(404).json({ msg: "Error al obtener producto:", error });
  }
};

